[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    'forge-std/=lib/forge-std/src/',
    'openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/',
    'safe-contracts/=lib/safe-contracts/contracts/',
]
verbosity = 3

# See more config options https://github.com/gakonst/foundry/tree/master/config
