[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    'forge-std/=lib/forge-std/src/',
    'openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/',
    'safe-contracts/=lib/safe-contracts/contracts/',
]
verbosity = 3
via-ir = true

solc_version = "0.8.17"

[profile.coverage]
via-ir = false

[rpc_endpoints]
mainnet = "https://eth-mainnet.alchemyapi.io/v2/${ALCHEMY_API_KEY}"
