[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    'ds-test/=lib/ds-test/src/',
    'openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/',
    'forge-std/=lib/forge-std/src/',
    '@gnosis-safe=node_modules/@gnosis.pm/safe-contracts/contracts'
]
verbosity = 3

# See more config options https://github.com/gakonst/foundry/tree/master/config